config/routes.rb
require "sidekiq/web"
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: "registrations", omniauth_callbacks:"omniauth_callbacks"}

  scope "(:locale)", :locale => /en/ do
    root "static_pages#home"
    get "home"=> "static_pages#home"
    get "about"=> "static_pages#about"
    get "contact"=> "static_pages#contact"

    namespace :supervisor do
      resources :subjects
      resources :users, only: [:index, :show, :destroy]
      resources :courses do
        resource :assign_trainee
        resource :assign_supervisor
      end
      resources :course_subjects, only: [:edit, :update]
      resources :users_courses
    end

    namespace :trainee do
      resources :users, only: [:index, :show, :destroy]
    end
    resources :user_subjects, only: [:index, :show, :update]
  end

  mount Sidekiq::Web, at: "/sidekiq"

end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable
  before_save { email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX =
    /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence:   true,
            format:     { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  #has_secure_password
  validates :password, presence: true, length: { minimum: 5 },
    allow_blank: true

  has_many :user_courses
  has_many :courses, through: :user_courses
  has_many :subjects, through: :courses
  has_many :user_tasks
  has_many :tasks, through: :user_tasks
  has_many :user_subjects
  has_many :course_subjects, through: :user_subjects

  scope :supervisors, -> {supervisor}
  scope :trainees, -> {trainee}

  enum role: [:supervisor, :trainee]

  class << self
    def from_omniauth auth
      where(provider: auth.provider,
        uid: auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.email = auth.info.email
        user.uid = auth.uid
        user.name = auth.info.name
      end
    end

    def new_with_session params, session
      if session["devise.user_attributes"]
        new(session["devise.user_attributes"],
          without_protection: true) do |user|
          user.attributes = params
          user.valid?
        end
      else
        super
      end
    end
  end

  def password_required?
    super && provider.blank?
  end

  def update_with_password params, *options
    if encrypted_password.blank?
      update_attributes params, *options
    else
      super
    end
  end

  include PublicActivity::Model
  tracked owner: ->(controller, model) {controller && controller.current_user}

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
end

app/controllers/supervisor/course_subjects_controller.rb
class Supervisor::CourseSubjectsController < ApplicationController
  
  def edit
    @course_subject = CourseSubject.find params[:id]
    @course = @course_subject.course
    @subject = @course_subject.subject
  end

  def update
    @course_subject = CourseSubject.find params[:id]
    if @course_subject.update_attributes course_subject_params
      @course = @course_subject.course
      flash[:success] = t :task_modified_successfully,
        course_name: @course_subject.course.name,
        subject_name: @course_subject.subject.name
      redirect_to [:supervisor, @course]
    else
      render :edit
    end
  end

  private
  def course_subject_params
    params.require(:course_subject).permit :id, :task_ids
  end
end

app/controllers/supervisor/courses_controller.rb
class Supervisor::CoursesController < ApplicationController
  before_action :load_course, except: [:index, :new, :create]
  authorize_resource

  def index
    @courses = Course.all
  end

  def edit
  end

  def update
    if params[:type] == "close"
      if @course.update_attributes status: Course.statuses[:close]
        flash[:success] = t :course_closed
        redirect_to [:supervisor, @course]
      else
        render :edit
      end
    else
      if @course.update_attributes course_params
        flash[:success] = t :course_update
        redirect_to [:supervisor, @course]
      else
        render :edit
      end
    end
  end

  def new
    @course = Course.new
    @subjects = Subject.all
  end

  def create
    @course = Course.new course_params
    if @course.save
      flash[:success] = t (:course_created)
      render :show
    else
      render :new
    end
  end

  def show
    @course = Course.find(params[:id])
  end

  def destroy
    @course.destroy
    flash[:success] = t :course_delete
    redirect_to supervisor_courses_path
  end

  private
  def course_params
    params.require(:course).permit(:name, :description, :start_date, :end_date, subject_ids: [] )
  end

  def load_course
    @course = Course.find params[:id]
  end

end

app/controllers/supervisor/subjects_controller.rb
class Supervisor::SubjectsController < ApplicationController
  before_action :load_user, only: [:index]
  before_action :load_activities, only: [:index]
  before_action :load_subject, only: [:show, :edit, :update, :destroy]
  authorize_resource
  def index
    @subjects = @user.subjects
  end

  def new
    @subject = Subject.new
    @subject.tasks.build
  end

  def create
    @subject = Subject.new subject_params
    if @subject.save
      flash.now[:success] = t :subject_creation_success
      render :show
    else
      render :new
    end
  end

  def show
    @subject_activities = PublicActivity::Activity.order("created_at desc").
       where(key:["subject.create","subject.update"], trackable_id: @subject.id)
  end

  def edit
  end

  def update
    if @subject.update_attributes subject_params
      flash[:success] = t :subject_update_success
      redirect_to [:supervisor, @subject]
    else
      flash.now[:danger] = t :subject_update_failure
      render :edit
    end
  end

  def destroy
    if @subject.destroy
      flash[:success] = t :subject_removal_success
      redirect_to supervisor_subjects_path
    else
      flash.now[:danger] = t :subject_removal_failure
      render :show
    end
  end

  private
  def load_user
    @user = User.first #Incompatibility 1: Please see SpecificationNotes.md
  end

  def load_subject
    @subject = Subject.find params[:id]
  end

  def subject_params
    params.require(:subject).permit :name, :description, tasks_attributes:
      [:id, :name, :description, :_destroy]
  end

  def load_activities
    @activities = PublicActivity::Activity.my_activity "subject.create"
  end
end

app/controllers/supervisor/users_controller.rb
class Supervisor::UsersController < ApplicationController
  before_action :load_user, only: [:show, :edit, :destroy]
  authorize_resource

  def index
    @users = User.supervisor
  end

  def new
  end

  def show
  end

  def edit
  end

  def destroy
   if @user.destroy
     flash[:success] = t(:success_message_delete)
     redirect_to supervisor_users_path
   end
  end

  private
    def load_user
      @user = User.find params[:id]
    end
end

app/controllers/supervisor/users_courses_controller.rb
class Supervisor::UsersCoursesController < ApplicationController
  before_action :load_course

  def show
  end

  def update
    if @course.update course_users_params
    flash[:success] = t (:successful_enrolled)
      redirect_to [:supervisor, @course]
    end
  end

  def destroy
  end

  private

  def course_users_params
    params.require(:course).permit user_ids: []
  end

  def load_course
    @course = Course.find params[:id]
  end

end

app/views/supervisor/courses/edit.html.erb
<% provide :title, t(:update_course)%>
<div class="center">
  <h1><%= t :update_course %></h1>
</div>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= form_for [:supervisor, @course] do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>

      <%= f.label :start_date %> <br>
      <%= f.date_select :start_date, class: "form-control" %> <br>

      <%= f.label :end_date %> <br>
      <%= f.date_select :end_date, class: "form-control" %> <br>

      <%= collection_check_boxes :course, :subject_ids, Subject.all, :id, :name %><br/>

      <%= f.submit t(:add_new_course), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/supervisor/courses/index.html.erb
<% provide :title, t(:all_course)%>
<div class="center">
  <h1><%= t :all_course %></h1><br/>
</div>

<table class="table table-bordered table-striped">

  <thead>
  <tr>
    <th><%= t (:course_name) %></th>
    <th><%= t (:course_description) %></th>
    <th><%= t (:course_start_date) %></th>
    <th><%= t (:course_end_date) %></th>
    <th><%= t (:course_status) %></th>
  </tr>
  </thead>

  <tbody>
  <% @courses.each do |course| %>
    <tr>
      <td><%= link_to course.name, [:supervisor, course]  %></td>
      <td><%= course.description.truncate 50 %></td>
      <td><%= course.start_date %></td>
      <td><%= course.end_date %></td>
      <td><%= course.status %></td>
    </tr>
  </tbody>

  <% end %>

</table>

app/views/supervisor/courses/new.html.erb
<% provide :title, t(:new_course)%>
<div class="center">
  <h1><%= t :new_course %></h1>
</div>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= form_for [:supervisor, @course] do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>

      <%= f.label :start_date %> <br>
      <%= f.date_select :start_date, class: "form-control" %> <br>

      <%= f.label :end_date %> <br>
      <%= f.date_select :end_date, class: "form-control" %> <br>

      <%= collection_check_boxes :course, :subject_ids, Subject.all, :id, :name %><br/>

      <%= f.submit t(:add_new_course), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/supervisor/courses/show.html.erb
<% provide :title, @course.name %>
<div class="center">
  <h1><%= t(:course_detail) %></h1>
</div>

<div class="row">
  <div class="panel panel-default panel-box">
    <div class="panel-heading panel-size-margin"><%= @course.name %>
      <div class="pull-right">
        <%= link_to t(:all_course), supervisor_courses_path, class: "btn btn-primary" %>
        <%= link_to t(:edit), edit_supervisor_course_path(@course), class: "btn btn-warning" %>
        <% unless @course.close? || @course.continue? %>
          <%= link_to t(:close), supervisor_course_path(@course, type: "close"), method: :patch,
            data: {confirm: t(:confirm_message_close)}, class: "btn btn-danger" %>
          <% end %>
        <% if @course.close? %>
          <%= link_to t(:delete_course), [:supervisor, @course], method: :delete,
            class: "btn btn-danger", data: {confirm: t(:confirm)} %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="center">
    <strong>
      <p><%= t (:start_date)%> <%= @course.start_date %></p>
      <p><%= t (:end_date)%> <%= @course.end_date %></p>
    </strong>
  </div>

  <div class="center bottom-aligned-row banner"><br/>
    <% if @course.open? %>
      <%= link_to t(:assign_supervisor), supervisor_users_courses_path, class: "btn btn-warning" %>
      <%= link_to t(:assign_trainee), supervisor_users_courses_path, class: "btn btn-warning" %>
    <% end %>
  </div>

  <div class="panel panel-default panel-box">
    <table class="table table-bordered table-striped">
      <thead>
      <tr>
        <th><%= t :subject_name %></th>
        <th><%= t :subject_description %></th>
        <th></th>
      </tr>
      </thead>

      <tbody>
      <% @course.subjects.each do |subject| %>
        <tr>
          <td><%= link_to subject.name, [:supervisor, subject]  %></td>
          <td><%= subject.description.truncate 50 %></td>
          <td>
            <% unless @course.close? %>
              <% course_subject = CourseSubject.find_by_course_id_and_subject_id(@course.id, subject.id) %>
              <%= link_to t(:manipulate_task),
                edit_supervisor_course_subject_path(course_subject), class: "btn btn-info" %>
            <% end %>
          </td>
        </tr>
        </tbody>

      <% end %>

      </table>
  </div>
</div>