config/routes.rb
require "sidekiq/web"
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: "registrations", omniauth_callbacks:"omniauth_callbacks"}

  scope "(:locale)", :locale => /en/ do
    root "static_pages#home"
    get "home"=> "static_pages#home"
    get "about"=> "static_pages#about"
    get "contact"=> "static_pages#contact"

    namespace :supervisor do
      resources :subjects
      resources :users, only: [:index, :show, :destroy]
      resources :courses do
        resource :assign_trainee
        resource :assign_supervisor
      end
      resources :course_subjects, only: [:edit, :update]
      resources :users_courses
    end

    namespace :trainee do
      resources :users, only: [:index, :show, :destroy]
    end
    resources :user_subjects, only: [:index, :show, :update]
  end

  mount Sidekiq::Web, at: "/sidekiq"

end

app/views/shared/_activity.html.erb
<% @activities.each do |activity| %>
  <%= link_to activity.owner.name, supervisor_user_path(activity.owner) if activity.owner %>
    <%= t :created_text %> <%= link_to activity.trackable.name, supervisor_subject_path(activity.trackable) if activity.trackable %>
      <%= t :at_text %>&nbsp<%= activity.created_at.to_s[0..-4] if activity.created_at %><br>
<% end %>

app/views/shared/_activity_subject_show.html.erb
<% if @subject_activities.any? %>
  <% @subject_activities.each do |activity| %>
    <%= link_to activity.owner.name, supervisor_user_path(activity.owner) if activity.owner %>
    <% if activity.key == "subject.create" %>
      <%= t :created_text %> <%= link_to activity.trackable.name, supervisor_subject_path(activity.trackable) if activity.trackable %>
    <% else %>
      <%= t :updated_text %> <%= link_to activity.trackable.name, supervisor_subject_path(activity.trackable) if activity.trackable %>
    <% end %>
    <%= t :at_text %>&nbsp<%= activity.created_at.to_s[0..-4] if activity.created_at %><br>
  <% end %>
<% end %>

app/views/shared/_activity_trainee_show.html.erb
<% if @trainee_task_activities_create.any? %>
  <% @trainee_task_activities_create.each do |activity| %>
    <%= link_to activity.owner.name, trainee_user_path(activity.owner) if activity.owner %>
    <%= t :completed_text %> <%= activity.trackable.task.name if activity.trackable %>
    <%= t :at_text %>&nbsp<%= activity.created_at.to_s[0..-4] if activity.created_at %></br>
  <% end %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t :form_contains %><%= pluralize(object.errors.count, t(:error)) %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_trainee_progress.html.erb
<div class="well">
  <h4>
    <%= t :course_completed_text %>(<%= course_completed_percentage %>%)
  </h4>
  <div class="progress">
    <div class="progress-bar progress-bar-success" role="progressbar"
      aria-valuenow="40" aria-valuemin="0" aria-valuemax="100"
      style="width:<%= course_completed_percentage %>%">
      <%= course_completed_percentage %> <%= t :completed_text_progress%>
    </div>
  </div>
</div>