config/routes.rb
require "sidekiq/web"
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: "registrations", omniauth_callbacks:"omniauth_callbacks"}

  scope "(:locale)", :locale => /en/ do
    root "static_pages#home"
    get "home"=> "static_pages#home"
    get "about"=> "static_pages#about"
    get "contact"=> "static_pages#contact"

    namespace :supervisor do
      resources :subjects
      resources :users, only: [:index, :show, :destroy]
      resources :courses do
        resource :assign_trainee
        resource :assign_supervisor
      end
      resources :course_subjects, only: [:edit, :update]
      resources :users_courses
    end

    namespace :trainee do
      resources :users, only: [:index, :show, :destroy]
    end
    resources :user_subjects, only: [:index, :show, :update]
  end

  mount Sidekiq::Web, at: "/sidekiq"

end

app/models/subject.rb
class Subject < ActiveRecord::Base
  has_many :course_subjects, dependent: :destroy
  has_many :courses, through: :course_subjects, autosave: true

  has_many :tasks, dependent: :destroy

  belongs_to :user_subject

  accepts_nested_attributes_for :tasks,
    reject_if:
      proc { |attributes| attributes["name"].blank? },
        allow_destroy: true

  validates :name, presence: true

  include PublicActivity::Model
  tracked except: :destroy, owner: ->(controller, model) {controller && controller.current_user}
end

app/controllers/supervisor/course_subjects_controller.rb
class Supervisor::CourseSubjectsController < ApplicationController
  
  def edit
    @course_subject = CourseSubject.find params[:id]
    @course = @course_subject.course
    @subject = @course_subject.subject
  end

  def update
    @course_subject = CourseSubject.find params[:id]
    if @course_subject.update_attributes course_subject_params
      @course = @course_subject.course
      flash[:success] = t :task_modified_successfully,
        course_name: @course_subject.course.name,
        subject_name: @course_subject.subject.name
      redirect_to [:supervisor, @course]
    else
      render :edit
    end
  end

  private
  def course_subject_params
    params.require(:course_subject).permit :id, :task_ids
  end
end

app/controllers/supervisor/courses_controller.rb
class Supervisor::CoursesController < ApplicationController
  before_action :load_course, except: [:index, :new, :create]
  authorize_resource

  def index
    @courses = Course.all
  end

  def edit
  end

  def update
    if params[:type] == "close"
      if @course.update_attributes status: Course.statuses[:close]
        flash[:success] = t :course_closed
        redirect_to [:supervisor, @course]
      else
        render :edit
      end
    else
      if @course.update_attributes course_params
        flash[:success] = t :course_update
        redirect_to [:supervisor, @course]
      else
        render :edit
      end
    end
  end

  def new
    @course = Course.new
    @subjects = Subject.all
  end

  def create
    @course = Course.new course_params
    if @course.save
      flash[:success] = t (:course_created)
      render :show
    else
      render :new
    end
  end

  def show
    @course = Course.find(params[:id])
  end

  def destroy
    @course.destroy
    flash[:success] = t :course_delete
    redirect_to supervisor_courses_path
  end

  private
  def course_params
    params.require(:course).permit(:name, :description, :start_date, :end_date, subject_ids: [] )
  end

  def load_course
    @course = Course.find params[:id]
  end

end

app/controllers/supervisor/subjects_controller.rb
class Supervisor::SubjectsController < ApplicationController
  before_action :load_user, only: [:index]
  before_action :load_activities, only: [:index]
  before_action :load_subject, only: [:show, :edit, :update, :destroy]
  authorize_resource
  def index
    @subjects = @user.subjects
  end

  def new
    @subject = Subject.new
    @subject.tasks.build
  end

  def create
    @subject = Subject.new subject_params
    if @subject.save
      flash.now[:success] = t :subject_creation_success
      render :show
    else
      render :new
    end
  end

  def show
    @subject_activities = PublicActivity::Activity.order("created_at desc").
       where(key:["subject.create","subject.update"], trackable_id: @subject.id)
  end

  def edit
  end

  def update
    if @subject.update_attributes subject_params
      flash[:success] = t :subject_update_success
      redirect_to [:supervisor, @subject]
    else
      flash.now[:danger] = t :subject_update_failure
      render :edit
    end
  end

  def destroy
    if @subject.destroy
      flash[:success] = t :subject_removal_success
      redirect_to supervisor_subjects_path
    else
      flash.now[:danger] = t :subject_removal_failure
      render :show
    end
  end

  private
  def load_user
    @user = User.first #Incompatibility 1: Please see SpecificationNotes.md
  end

  def load_subject
    @subject = Subject.find params[:id]
  end

  def subject_params
    params.require(:subject).permit :name, :description, tasks_attributes:
      [:id, :name, :description, :_destroy]
  end

  def load_activities
    @activities = PublicActivity::Activity.my_activity "subject.create"
  end
end

app/controllers/supervisor/users_controller.rb
class Supervisor::UsersController < ApplicationController
  before_action :load_user, only: [:show, :edit, :destroy]
  authorize_resource

  def index
    @users = User.supervisor
  end

  def new
  end

  def show
  end

  def edit
  end

  def destroy
   if @user.destroy
     flash[:success] = t(:success_message_delete)
     redirect_to supervisor_users_path
   end
  end

  private
    def load_user
      @user = User.find params[:id]
    end
end

app/controllers/supervisor/users_courses_controller.rb
class Supervisor::UsersCoursesController < ApplicationController
  before_action :load_course

  def show
  end

  def update
    if @course.update course_users_params
    flash[:success] = t (:successful_enrolled)
      redirect_to [:supervisor, @course]
    end
  end

  def destroy
  end

  private

  def course_users_params
    params.require(:course).permit user_ids: []
  end

  def load_course
    @course = Course.find params[:id]
  end

end

app/views/supervisor/subjects/_tasks_form.html.erb
<div class="jumbotron">
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :description %>
  <%= f.text_area :description, class: "form-control" %>

  <%= link_to_remove_fields t(:remove), f %>
</div>

app/views/supervisor/subjects/edit.html.erb
<h2><%= t :edit_subject %></h2>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:supervisor, @subject] do |f| %>
      <%= render "shared/error_messages", object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :description %>
      <%= f.text_area :description, class: "form-control" %>

      <h3><%= t :tasks %></h3>

      <%= f.fields_for :tasks do |builder| %>
        <%= render "tasks_form", f: builder %>
      <% end %>
      <p><%= link_to_add_fields t(:add_tasks), f, :tasks %></p>

      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/supervisor/subjects/index.html.erb
<h1><%= t :subjects %></h1>
<div class="row">
  <div class="col-sm-7 col-sm-offset-0">
    <% if !(@subjects.empty?) %>
    <% @subjects.each do |subject| %>
      <div class="jumbotron">
        <%= link_to supervisor_subject_path(subject) do %>
          <h2><%= subject.name %></h2>
        <% end %>
        <p><%= subject.description %></p>
      </div>
    <% end %>
    <% else %>
      <div class="jumbotron">
        <p><%= t :subject_empty %></p>
      </div>
    <% end %>
  </div>
  <div class=".col-sm-5 pull-right">
    <div class="panel panel-default pull-right">
      <div class="panel-heading"><%= t :activity_text %></div>
      <div class="panel-body">
        <%= render "shared/activity" %>
      </div>
    </div>
  </div>
</div>

app/views/supervisor/subjects/new.html.erb
<h2><%= t :create_subject %></h2>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:supervisor, @subject] do |f| %>
      <%= render "shared/error_messages", object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :description %>
      <%= f.text_area :description, class: "form-control" %>

      <h3><%= t :tasks %></h3>

      <%= f.fields_for :tasks do |builder| %>
        <%= render "tasks_form", f: builder %>
      <% end %>
      <p><%= link_to_add_fields t(:add_tasks), f, :tasks %></p>

      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/supervisor/subjects/show.html.erb
<h1><%= @subject.name %></h1>

<div class="row">
  <div class="col-sm-6">
    <%= link_to supervisor_subject_path(@subject), method: :delete, data: { confirm: (t :remove_confirmation) } do %>
      <button type="button" class="btn btn-lg btn-danger pull-right"><%= t :delete %></button>
    <% end %>
    <%= link_to edit_supervisor_subject_path(@subject) do %>
      <button type="button" class="btn btn-lg btn-default pull-right"><%= t :edit %></button>
    <% end %>

    <hr>

    <p><%= @subject.description %></p>
    <h3><%= t :appears_in %></h3>
    <table class="table">
      <thead>
      <tr>
        <th><%= t :course %></th>
        <th><%= t :deadline %></th>
      </tr>
      </thead>
      <tbody>
      <% @subject.courses.each do |course| %>
        <tr>
          <td>
            <%= link_to '#' do %> <!-- supervisor_course_path(course) -->
              <%= course.name %>
            <% end %>
          </td>
          <td><%= t :not_impleted_votice %></td>
        </tr>
      <% end %>
      </tbody>
    </table>

    <h3><%= t :trainees %></h3>
    <table class="table">
      <thead>
      <tr>
        <th><%= t :name %></th>
        <th><%= t :email %></th>
      </tr>
      </thead>
      <tbody>
      <% @subject.users.trainee.each do |user| %>
        <tr>
          <td>
            <%= link_to '#' do %> <!-- supervisor_user_path(user) -->
              <%= user.name %>
            <% end %>
          </td>
          <td><%= user.email %></td>
        </tr>
      <% end %>
      </tbody>
    </table>

    <h3><%= t :supervisors %></h3>
    <table class="table">
      <thead>
      <tr>
        <th><%= t :name %></th>
        <th><%= t :email %></th>
      </tr>
      </thead>
      <tbody>
      <% @subject.users.supervisor.each do |user| %>
        <tr>
          <td>
            <%= link_to '#' do %> <!-- supervisor_user_path(user) -->
              <%= user.name %>
            <% end %>
          </td>
          <td><%= user.email %></td>
        </tr>
      <% end %>
      </tbody>
    </table>

  </div>
  <div class=".col-sm-6 pull-right">
    <div class="panel panel-default pull-right">
      <div class="panel-heading"><%= t :activity_text %></div>
      <div class="panel-body">
        <%= render "shared/activity_subject_show" %>
      </div>
    </div>
  </div>
</div>