config/routes.rb
require "sidekiq/web"
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: "registrations", omniauth_callbacks:"omniauth_callbacks"}

  scope "(:locale)", :locale => /en/ do
    root "static_pages#home"
    get "home"=> "static_pages#home"
    get "about"=> "static_pages#about"
    get "contact"=> "static_pages#contact"

    namespace :supervisor do
      resources :subjects
      resources :users, only: [:index, :show, :destroy]
      resources :courses do
        resource :assign_trainee
        resource :assign_supervisor
      end
      resources :course_subjects, only: [:edit, :update]
      resources :users_courses
    end

    namespace :trainee do
      resources :users, only: [:index, :show, :destroy]
    end
    resources :user_subjects, only: [:index, :show, :update]
  end

  mount Sidekiq::Web, at: "/sidekiq"

end

app/models/user_subject.rb
class UserSubject < ActiveRecord::Base
  belongs_to :user
  belongs_to :course_subject

  has_one :subject, through: :course_subject
  has_many :user_tasks
  accepts_nested_attributes_for :user_tasks, reject_if:
    proc {|attributes| attributes[:task_id]=='0'}, allow_destroy: true
  has_many :tasks, through: :user_tasks

  scope :completed_tasks, ->(current_user){where(user_id: current_user.id, status:
    UserSubject.statuses[:finished])}
  scope :total_tasks, ->(current_user){where(user_id: current_user.id)}

  enum status: [ :_new, :finished ]
  scope :course_subject, ->(course_subject){
    find_by( "course_subject_id = ?", course_subject.id )}
end

app/controllers/user_subjects_controller.rb
class UserSubjectsController < ApplicationController
  before_action :load_status, only: [:show, :update]
  before_action :load_user, only: :index

  def index
    @subjects = @user.subjects
  end

  def show
    @new_tasks.count.times { @user_subject.user_tasks.build }
  end

  def update
   begin
      @user_subject.update_attributes user_subject_params
      flash[:success] = t :task_update_success
    rescue
      flash[:danger] = t :task_update_failure
    end
    redirect_to @user_subject
  end

  private
  def load_user
    @user = User.first # Incompatibility 1: Please see SpecificationNotes.md
  end

  def load_dependencies
    load_user
    @user_subject = @user.user_subjects.find params[:id]
    @subject = @user_subject.subject
    @tasks = @subject.tasks
    @user_tasks = @user_subject.tasks
    @new_tasks=Array.new
    @tasks.each {|task| @new_tasks<<task if @user_tasks.exclude? task}
  end

  def load_status
    load_dependencies
    @status=[]
    course_subject = @user_subject.course_subject
    user_subject_status = @user_subject.status
    course_subject_status = course_subject.status
    if course_subject_status == :finished
      @status<<course_subject_status
    else
      @status<<user_subject_status
    end
    @status<<
        course_subject.course.start_date.to_date<<
        course_subject.course.end_date.to_date
  end

  def user_subject_params
    params.require(:user_subject).permit user_tasks_attributes: [:id,
      :user_id, :task_id, :_destroy]
  end
end

app/views/user_subjects/index.html.erb
<h1><%= t :user_subject %></h1>
<div class="row">
  <div class="col-sm-7 col-sm-offset-0">
    <% if !@subjects.empty? %>
      <% @subjects.each do |subject| %>
        <div class="jumbotron">
          <%= link_to user_subject_path subject do %>
            <h2><%= subject.name %></h2>
          <% end %>
          <p><%= subject.description %></p>
        </div>
      <% end %>
    <% else %>
      <div class="jumbotron">
        <p><%= t :subject_empty_user %></p>
      </div>
    <% end %>
  </div>
  <div class=".col-sm-2 pull-right">
    <div class="panel panel-default pull-right">
      <div class="panel-heading"><%= t :activity_text %></div>
      <div class="panel-body">
        <!-- TODO: Implement Activity Here -->
      </div>
    </div>
  </div>
</div>

app/views/user_subjects/show.html.erb
<h2><%= @user_subject.subject.name %></h2>

<div class="row">
  <div class="col-sm-8">
    <%= form_for @user_subject do |f| %>
      <%= f.fields_for :user_tasks do |builder| %>
        <%= builder.hidden_field :user_id, value: @user.id %>
        <% if builder.object.task_id %>
          <%= builder.label :task_id, builder.object.task.name %>
          <%= builder.check_box :task_id, {checked: true, disabled: true},
            checked_value=builder.object.task_id %>
        <% else %>
          <%= builder.label :task_id, @new_tasks.first.name %>
          <%= builder.check_box :task_id, {checked: false, disabled:
            @user_subject.finished?}, checked_value=@new_tasks.first.id %>
          <% @new_tasks.shift %>
        <% end %>
      <% end %>

      <% if @user_subject._new? %>
        <%= f.submit %>
      <% end %>
    <% end %>
    <hr>
    <h3><%= t :basic %></h3>
    <p><%= t :start_date %>: <%= @status[1] %></p>
    <p><%= t :end_date %>: <%= @status[2] %></p>
    <p><%= t :status %>: <%= @status[0].humanize %></p>

    <h3><%= t :instruction %></h3>(<%= link_to t(:hide), '#',
      html_options={ class: "swap_btn" } %>)
    <p class="inst" ><%= @user_subject.subject.description %></p>
  </div>
  <div class="col-sm-2">
    <h3><% t :activity_log %></h3>
    <!-- PLACEHOLDER: Progress -->
  </div>
</div>